### ISSUE TITLE
是否考虑增加鼠标穿透功能

### ISSUE THREAD

**Issue by FangDingli** [Beats0/bilive-danmaku#12]
似乎可以用setIgnoreMouseEvents这个API让窗口实现鼠标穿透，否则游戏的时候点到弹幕窗口就变成在操作弹幕框了。

**Comment by Beats0** [comment]
增加到下个版本吧

**Comment by Beats0** [comment]
已添加

[v1.0.8](https://github.com/Beats0/bilive-danmaku/releases/tag/v1.0.8) 版本已发布
