### ISSUE TITLE
希望增加修改字体的功能

### ISSUE THREAD

**Issue by likanglian** [Beats0/bilive-danmaku#2]
可以用于mac的弹幕姬找了很久，非常好用。但是，现在的默认字体并不便于阅读，希望增加切换功能，谢谢。

**Comment by Beats0** [comment]
最近都比较忙，估计会要很久之后才会更新了

**Comment by Beats0** [comment]
已添加

[v1.0.6](https://github.com/Beats0/bilive-danmaku/releases/tag/v1.0.6) 版本已发布
